global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'app'
    static_configs:
      - targets: ['localhost:9921']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['localhost:9922']

