global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'app'
    static_configs:
      - targets: ['group16:8000']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['group16:9100']